# Generated by Django 2.2.6 on 2019-10-30 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perimeters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perimeter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_perimeters', to=settings.AUTH_USER_MODEL),
        ),
    ]
