# Generated by Django 2.2.6 on 2019-10-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0002_auto_20191021_1450'),
        ('checkpoint', '0002_auto_20191021_1450'),
        ('patrolpoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolpoint',
            name='user',
        ),
        migrations.AddField(
            model_name='patrolpoint',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkpoint.CheckPoint'),
        ),
        migrations.AddField(
            model_name='patrolpoint',
            name='patrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patrol.Patrol'),
        ),
    ]
