# Generated by Django 2.2.6 on 2019-10-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0002_auto_20191021_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
