# Generated by Django 2.2.6 on 2019-10-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perimeters', '0001_initial'),
        ('floors', '0002_auto_20191020_2215'),
        ('checkpoint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='user',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='floors.Floor'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='perimeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perimeters.Perimeter'),
        ),
    ]
