# Generated by Django 2.2.6 on 2019-10-26 15:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoint', '0002_auto_20191021_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='floor',
            field=models.ForeignKey(blank=True, help_text='The perimeter floor is essential to ditinguish points that are geometrically ontop of each other', null=True, on_delete=django.db.models.deletion.CASCADE, to='floors.Floor'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='geo_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, max_length=255, null=True, srid=4326),
        ),
    ]
