# Generated by Django 2.2.6 on 2019-10-20 22:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Floors',
            new_name='Floor',
        ),
    ]
